## COMP3670 Programming Assignment 1 - Linear Algebra
---

**Enter Your Student ID:** 

**Your Name:**
    
**Deadline:**

**Submit:** Write your answers in this file, and submit a single Jupyter Notebook file (.ipynb) on Wattle. Rename this file with your student number as 'uXXXXXXX.ipynb'.

**Enter Discussion Partner IDs Below:**
You could add more IDs with the same markdown format above.



---
**Marking distribution for the assignment**

- Task1 = 10%
- Task2 = 50%
- Task3 = 40%

**You will get full marks if your program passes all the tests; you will get partial marks if it passes some cases. There is no process marks (we do not look into your codes).**

## Task 0: Introduction
---

**NOTE:** *This part of the first assignment is by necessity somewhat tedious as its primary purpose is to introduce syntax, how to access and understand the Numpy documentation and some very basic concepts. If you are already familiar with Numpy, you can just read the **TASK** headings and complete the questions without worrying about all the additional information. This is designed for people who have never seen Numpy before, so it's a very easy 1st year style introduction to just introduce syntax.*

*As this is a third year subject, it is assumed you already know to to program well (but may be unfamiliar with Python and Numpy).*

---

Arguably the most fundamental tool needed to engage with machine learning in Python is Numpy *(np)*. To include Numpy in any project, simply type the following line at the top of your python file:

In [1]:
# numpy
import numpy as np

!pip install sympy
import sympy as sp

# matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

A Jupyter Notebook is divided into cells, each of which works like a Python module or Latex file. When a cell is run, any cells that follow it will have access to its results. Running the above cell will give all following cells access to the Numpy library.

-----------

   **TASK 0.1:** To run the above cell, select it by clicking on it, hold **shift** and press **return**. If you have succeeded, then the cell will print "Done" just above.


-----------

Numpy is a library of common mathematical data structures and algorithms used in machine learning. For example:

- It allows you to declare vectors and matrices, with all the associated mathematical operations like matrix vector products, matrix addition / subtraction.
- It provides convenient, efficient implementations of algorithms to solve matrix equations, find the inverse of a matrix or perform Eigen decomposition. The implementation of these algorithms is compiled from C code, making Numpy much faster than programming these algorithms yourself in Python.

You'll need to know Numpy inside and out. We'll start by getting you familiar with the easy to access online documentation and performing a few basic operations.

Below I have declared the matrices: 

$$A = 
\begin{bmatrix}
2&3\\
0&1\\
\end{bmatrix}
\\
x = 
\begin{bmatrix}
1\\
3\\
\end{bmatrix}
$$. 

---
**TASK 0.2:** Run the cell below and observe what it prints.


---
(If it throws an error, you have the wrong version of python installed. This entire course will use Python 3, not Python 2)



In [2]:
A = np.array([[2, 3], [0, 1]])
x = np.array([[1], [3]])

#Matrix Multiplication Example
b = A @ x
print('\nMatrix Multiplication')
print(b)


Matrix Multiplication
[[11]
 [ 3]]


The above code illustrates how to perform matrix multiplication. Memorise it. Below are some other basic operations you'll likely need over the coming semester:

In [3]:
#Matrix Addition Example
b = A + x
print('\nMatrix Addition')
print(b)

#Elementwise Multiplication Example
b = A * x
print('\nElementwise Matrix Multiplication')
print(b)

#Extract a single element of a matrix:
print('\nSingle Element Extraction')
b = A[0, 0]
print(b)

#Extract an entire column of a matrix:
print('\nColumn Extraction')
b = A[:, 0]
print(b)

#Extract an entire row of a matrix:
print('\nRow Extraction')
b = A[0, :]
print(b)

#Transpose of a matrix:
print('\nTranspose')
A_Transpose = A.T
print(A_Transpose)


Matrix Addition
[[3 4]
 [3 4]]

Elementwise Matrix Multiplication
[[2 3]
 [0 3]]

Single Element Extraction
2

Column Extraction
[2 0]

Row Extraction
[2 3]

Transpose
[[2 0]
 [3 1]]


## Task1: Solving a system of linear equations
---

A vital part of linear algebra is to know how to solve a system of linear equations. For e.g. 

$$a_{11}x_1+a_{12}x_2 \dots a_{1d}x_d=b_1$$
$$a_{21}x_1+a_{22}x_2 \dots a_{2d}x_d=b_2$$
$$\vdots$$
$$a_{n1}x_1+a_{n2}x_2 \dots a_{nd}x_d=b_n$$

The above system of linear equations can also be written down in a compact matrix form as follows:

$$AX = B$$

where,
$$A = \begin{bmatrix}
a_{11} & \dots & a_{1d}\\
\vdots & \ddots & \vdots \\
a_{n1} & \dots & a_{nd}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_1 \\ \vdots \\ b_n
\end{bmatrix}, \quad
X = \begin{bmatrix}
x_1 \\ \vdots \\ x_d
\end{bmatrix}.
$$

---
**Task 1.1**: Use numpy's solve function to compute X

---
**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

In [4]:
# define A,B
A = np.array([[10, 14, 4], [15, 2, 6], [7, 8, 18]])
B = np.array([[2], [1], [2]])

def solve_with_numpy(A,B):
    # TODO: solve the linear system
    return np.linalg.solve(A, B)

# show solution
X = solve_with_numpy(A,B)
print (X)

[[0.03185596]
 [0.10526316]
 [0.05193906]]


A more hands on way for solving for X, involves computing first computing the inverse of the matrix $A$

---
**Task 1.2**: Use numpy's inbuilt method for computing the inverse of the matrix $A$

---

**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

In [5]:
A = np.array([[7, 1], [15, 4]])

def find_inverse(A):
    # TODO: find the inverse of the matrix A
    return np.linalg.inv(A)
    
A_inv = find_inverse(A)
print(A_inv)

[[ 0.30769231 -0.07692308]
 [-1.15384615  0.53846154]]


---
**Task 1.3**: Use the inverse of matrix $A$, to solve for $X$. **Note that you are only allowed to use the functions in 1.1 and 1.2. No other library functions are allowed**.

---

In [6]:
A = np.array([[5, 3], [2, 11]])
B = np.array([[16], [5]])

def solve_with_prev_tasks(A, B):
    # TODO: solve the linear system using functions you have written
    return np.linalg.inv(A) @ B

X = solve_with_prev_tasks(A, B)
print(X)

[[ 3.28571429]
 [-0.14285714]]


But what if $A$ is not a square matrix?

---
**Task 1.4**: Compute the Moore-Penrose pseudo inverse for matrix $A$ and **use it to solve for $x$**. **Note that, you must not directly use `np.linalg.pinv` for computing the pseudo-inverse**.

---

In [7]:
A = np.array([[15, 1], [5, 10], [8, 2], [11, 19]])
B = np.array([[18], [15], [2], [8]])

def pseudo_inverse(A):
    # TODO: find the pseudo inverse of a matrix
    return np.linalg.inv(A.T@A)@A.T

def solve_with_pseudo_inverse(A, B):
    A_pseudo = pseudo_inverse(A)
    # TODO: solve for x using pseudo inverse method.
    return A_pseudo @ B

X = solve_with_pseudo_inverse(A, B)
    
# print(np.linalg.pinv(A))
print(X)

[[0.97187421]
 [0.09046455]]


## Task 2: Solving a system of linear equations with Gaussian elimination

In the last task, we used numpy's inbulit functions to solve a system of linear equations. Lets do it without using these functions!

---
**Task 2.1**:  Complete the following gaussian elimnation function to compute the **reduced row-echelon form** of matrix $A$. You must implement the gaussian elimination algorithm yourself, not merely call someone else's library function. You **MUST NOT** copy codes from any source. Your function needs to work under **different shapes** of matrix. Negative zero is a result of the floating-point number standard. If you have some -0s instead of 0s, that should be fine.

---

In [8]:
def gaussian_elim(X):
    m, n = X.shape
    res = np.array(X, dtype=np.float64)
    h = 0
    k = 0
    lead = 0
    while h < res.shape[0] and k < res.shape[1]:
        i_max = np.argmax(np.abs(res[h:, k])) + h
        if abs(res[i_max][k]) < 1e-10:
            k += 1
        else:
            tmp = np.copy(res[h])
            res[h] = res[i_max]
            res[i_max] = tmp
            for i in range(h + 1, res.shape[0]):
                f = res[i][k] / res[h][k]
                res[i][k] = 0
                res[i][k + 1:] -= res[h][k + 1:] * f
            h += 1
            k += 1
            lead += 1
    while lead > 0:
        h = lead - 1
        for i in range(0, res.shape[1]):
            if abs(res[h][i]) > 1e-10:
                pivot = res[h][i]
                pivot_arg = i
                break
        res[h] = res[h] / pivot
        for i in range(0, h):
            f = res[i][pivot_arg]
            res[i] = res[i] - f * res[h]
        lead -= 1
    # Do not change the following line
    res[abs(res) < 1e-10] = 0
    return res

In [9]:
A = np.array([[18, 18, 14, 15, 14, 19,  8,  7,  2, 11],
               [ 3,  7,  8,  8,  2,  2,  8, 17,  6,  8],
               [ 2,  8,  6,  4, 11, 10, 15, 11, 12,  3],
               [ 9,  4, 17,  6,  6, 12, 13,  0, 12,  2],
               [ 0,  3, 18,  0, 13,  6,  8, 13, 16, 15],
               [15, 16, 13,  9,  4, 17, 11,  0,  5, 18],
               [10,  4,  6, 12,  6, 18, 17,  7,  5,  6],
               [ 3, 12,  2,  4, 16,  1, 17,  8, 10,  2],
               [ 7,  8, 11,  4, 12, 14, 18, 14,  9, 16],
               [18, 13,  3, 19, 16,  9,  6,  8,  2, 15]])

print(gaussian_elim(A))

# The result should be an identity matrix

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
B = np.array([[ 5,  3, 14,  1,  2, 15,  1, 11],
               [ 3, 13,  5, 18, 16, 18, 12,  4],
               [ 1,  9, 12, 15, 15,  0,  7,  0],
               [18, 17,  5,  0, 11,  4, 17,  9]])

print(gaussian_elim(B))
# The result should look like
# [[  1.           0.           0.           0.          -2.77442593 20.86492571  -0.07248987   7.64520486]
#  [  0.           1.           0.           0.           3.44146781 -21.02183701   1.11661414  -7.36402521]
#  [  0.           0.           1.           0.           0.48694282 -2.83948672  -0.13552454  -0.68505178]
#  [  0.           0.           0.           1.          -1.26947321 13.49369653  -0.09004953   4.45677623]]

[[  1.           0.           0.           0.          -2.77442593
   20.86492571  -0.07248987   7.64520486]
 [  0.           1.           0.           0.           3.44146781
  -21.02183701   1.11661414  -7.36402521]
 [  0.           0.           1.           0.           0.48694282
   -2.83948672  -0.13552454  -0.68505178]
 [  0.           0.           0.           1.          -1.26947321
   13.49369653  -0.09004953   4.45677623]]


In [11]:
C = np.array([[ 3, 12, 17],
               [14, 19,  8],
               [ 1, 12,  7],
               [10, 17, 11],
               [ 6,  0, 12],
               [16,  3, 15],
               [16, 19, 18]])

print(gaussian_elim(C))
# The result should look like
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---
**Task 2.2**: A system of linear equations is called homogeneous if the right hand side is the zero vector. Sometimes there will be only trivial solution, namely the zero vector. An example of this matrix is:
$$2x_1+4x_2 =0$$
$$2x_1+5x_2 =0$$
Sometimes there will be non-trivial solutions, e.g.,
$$2x_1+4x_2 =0$$
$$1x_1+2x_2 =0$$
The solution can be $x_1 =-2$, $x_2 =1$.
 
$A=\big(\begin{smallmatrix}
  2 & 4\\
  1 & 2
\end{smallmatrix}\big)$ is called coefficient matrix.
Your task is solving a homogeneous system of linear equations based on its reduced row-echelon form, i.e., the output of your *gaussian_elim* function in Task 2.1. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1. Your function needs to work under **different shapes** of $A$. 

The *solve_homogeneous* function should be according to the following specifications:
* Take as input the coefficient matrix $A$. 
* Return:
    - 0 if it only has trivial solution. Type: int.
    - otherwise, return any two different non-trivial solutions. Type: tuple((np.ndarray, Type: np.ndarray)).  Note that the dimensions of the np.ndarray should be 1, i.e., using one pair of square brackets. See demo outputs below.

In [12]:
def find_pivot_pos(rref, m, n):
    pivot_pos = []
    for i in range(m):
        pos = np.where(rref[i] == 1)[0]
        if len(pos) > 0:
            pivot_pos.append(pos[0])
    free_var_pos = [p for p in range(n - 1) if p not in pivot_pos]
    return pivot_pos, free_var_pos


# solve homogeneous or non-homogeneous system of equations when they have one or more solutions
def solve(rref):
    m, n = rref.shape
    pivot_pos, free_var_pos = find_pivot_pos(rref, m, n)
    res = [[0 for _ in range(n - len(pivot_pos))] for _ in range(n - 1)]
    i = 0
    while i <= m - 1:
        j = 0
        while j <= n - 2:
            if rref[i, j] == 1 and j in pivot_pos:
                pj = j
                res[j][0] = rref[i, n - 1]
            if rref[i, j] != 0 and j not in pivot_pos:
                k = free_var_pos.index(j) + 1
                res[pj][k] = -rref[i, j]
            j += 1
        i += 1
    k = 1
    j = 0
    while j <= n - 2:
        if j in free_var_pos:
            res[j][k] = 1
            k += 1
        j += 1
    return np.array(res)

In [13]:
def solve_homogeneous(A):
    m, n = A.shape
    rref = gaussian_elim(A)
    rank = 0
    for i in range(m):
        if np.any(rref[i]):
            rank += 1
    if rank == n:
        return 0
    else:
        rref = np.column_stack((rref, np.zeros(m)))
        res = solve(rref)
        return np.sum(res, axis=1), 2 * np.sum(res, axis=1)

In [14]:
A = np.array([[ 6,  9,  1,  7],
               [17,  1,  3, 17],
               [ 8,  4,  9, 13],
               [18,  4, 18, 18]])
print(solve_homogeneous(A))
# The result should look like
# 0

0


In [15]:
B = np.array([[ 6,  8,  6, 15, 12],
           [17,  8,  8, 12,  2],
           [18, 15, 15,  7,  2],
           [ 7,  6, 10,  3, 18],
           [14,  4,  4,  2, 16]])
print(solve_homogeneous(B))
# The result should look like
# 0

0


In [16]:
C = np.array([[ 8, 18, 18],
               [14, 19, 15],
               [4,  9,  9]])

print(solve_homogeneous(C))
# The result should look like
# (array([ 0.72, -1.32,  1.  ]), array([ 1.44, -2.64,  2.  ]))
# Note they are not unique

(array([ 0.72, -1.32,  1.  ]), array([ 1.44, -2.64,  2.  ]))


In [17]:
D = np.array([[10,  3,  2,  8],
           [16,  5,  8,  5],
           [ 0,  0, 13, 16]])

print(solve_homogeneous(D))
#The result should look like
# ((array([-21.11538462,  68.53846154,  -1.23076923,   1.        ]), 
# array([-42.23076923, 137.07692308,  -2.46153846,   2.        ]))
# Note they are not unique

(array([-21.11538462,  68.53846154,  -1.23076923,   1.        ]), array([-42.23076923, 137.07692308,  -2.46153846,   2.        ]))


In [18]:
E = np.array([[ 2, 12,  2],
           [12,  8,  7],
           [14,  5, 17],
           [ 8, 10,  5]])

print(solve_homogeneous(E))
# The result should look like
# 0

0


---
**Task 2.3**: A system of linear equations is called non-homogeneous if the right hand side is not the zero vector. A non-homogeneous system of linear equations has
* no solution, or
* a unique solution, or
* infinite number of solutions

Similar to Task 2.2, your task is solving a non-homogeneous system of linear equations. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1, however, you are allowed to use the functions you defined in Task 2.2. Your function needs to work under **different shapes** of augmented matrix $[A|b]$. 

The *solve_nonhomogeneous* function should be according to following specifications:
* Take as input the augmented matrix $[A|b]$. 
* Return:
    - None if it has no solution at all. Type: None.
    - the single solution if it only has one solution. Type: np.ndarray.
    - otherwise, return any two different solutions if it has more than one solutions. Type: tuple((np.ndarray, Type: np.ndarray)).
*  Note that the dimensions of the np.ndarray should be 1, especially, one pair of square brackets. See demo outputs below.    

In [19]:
def solve_nonhomogeneous(A_aug):
    rref = gaussian_elim(A_aug)
    rank_A, rank_aug = 0, 0
    for i in range(A_aug.shape[0]):
        if np.any(rref[i]):
            rank_aug += 1
        if np.any(rref[i][:-1]):
            rank_A += 1
    if rank_A != rank_aug:
        return None
    else:
        res = solve(rref)
        if res.shape[1] == 1:
            return np.squeeze(res)
        else:
            return res[:, 0] + np.sum(res[:, 1:],axis=1), res[:, 0] + 2 * np.sum(res[:, 1:],axis=1)

In [20]:
A = np.array([[ 9,  5, 14,  3],
           [ 9,  1, 11,  0],
           [ 0,  4,  3,  2]])

print(solve_nonhomogeneous(A))
# The result should look like
# None

None


In [21]:
B = np.array([[ 9, 19,  2, 18],
           [ 5,  7,  3, 14],
           [14,  6,  1,  9]])

print(solve_nonhomogeneous(B))
# The result should look like
# [0.19444444 0.52777778 3.11111111]

[0.19444444 0.52777778 3.11111111]


In [22]:
C = np.array([[14, 14,  0, 18,  2, 11],
           [12, 12,  5,  1, 19, 13],
           [ 9,  3,  7,  1,  2, 11],
           [18, 10,  6, 12,  8, 16]])
print(solve_nonhomogeneous(C))
# The result should look like
# (array([-2.99214286,  0.35642857,  4.61571429,  2.55      ,  1.        ]), 
# array([-6.15785714,  0.29357143,  8.08428571,  4.95      ,  2.        ]))
# The results are not unique

(array([-2.99214286,  0.35642857,  4.61571429,  2.55      ,  1.        ]), array([-6.15785714,  0.29357143,  8.08428571,  4.95      ,  2.        ]))


## Task 3: Rank, Basis and Span

Given a matrix $X$, would it be possible for you to programmably determine its rank, null space and column space? In this question, you are tasked at **1) finding the rank and the dimension of the null space $X$, 2) finding the basis that spans the column space of $X$, and 3) finding the basis that spans the null space of $X$.**

---
**Task 3.1**: Implement two functions `rank`, `dim_null`.

`rank`: takes arbitrary matrix $X$ as input, output its rank.

`dim_null`: takes arbitrary matrix $X$ as input, output the dimension of its null space

**Note: If you didn't get Gaussian Elimination in task2, you may use the library function `sp.Matrix(X).rref()` to get the reduced row echelon form of $X$. But, you must not use other library functions that can solve questions directly.**

In [23]:
def rank(A):
    # TODO: get rank of A
    m, n = A.shape
    A = gaussian_elim(A)
    pivot_pose, _ = find_pivot_pos(A, *A.shape)
    return len(pivot_pose)
    
def dim_null(A):
    # TODO: get dimension of the null space of A
    n = A.shape[1]
    return n - rank(A)

In [24]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(rank(A))
print(dim_null(A))

# you should get
# 0
# 3

0
3


In [25]:
B = np.array([[16,  8, 12,  8,  5],
               [ 0,  7,  9, 14,  2],
               [14, 12, 13, 15, 14],
               [13, 18, 16, 19, 12]])

print(rank(B))
print(dim_null(B))

# you should get
# 4
# 1

4
1


In [26]:
C = np.array([[ 1,  8,  4],
               [ 0,  0, 11],
               [15,  2, 11],
               [12,  0,  3]])

print(rank(C))
print(dim_null(C))

# you should get
# 3
# 0

3
0




---
**Task 3.2**: Implement `basis_col`.

`basis_col`: takes arbitrary matrix $X$ as input, output a basis that spans the column space of $X$. The basis should be a numpy array or a list, containing several numpy array vectors. 

---

In [28]:
def basis_col(A):
    # TODO: get a basis for the column space.
    A_ = gaussian_elim(A)
    pivot_pose, _ = find_pivot_pos(A_, *A_.shape)
    if pivot_pose == []:
        return np.zeros_like([A[:, 0]]).T
    return A[:, pivot_pose]

In [29]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(basis_col(A))

# should return 
# array([[0], [0], [0]])

[[0]
 [0]
 [0]]


In [30]:
B = np.array([[13, 11,  6,  9,  6],
            [ 0, 12, 16, 11, 14],
            [ 5, 15,  8,  3,  0],
            [16,  3,  1, 14,  5]])

print(basis_col(B))

# should return something like
# array([[13, 11, 6, 9], [0, 12, 16, 11], [5, 15, 8, 3], [16, 3, 1, 14]])
# the solution is not unique

[[13 11  6  9]
 [ 0 12 16 11]
 [ 5 15  8  3]
 [16  3  1 14]]


In [31]:
C = np.array([[1, 1], 
              [1, 1], 
              [1, 1]])

print(basis_col(C))
# should return something like
# array([[1], [1], [1]])
# the solution is not unique

[[1]
 [1]
 [1]]


---
**Task 3.3**: Implement `basis_null`.

`basis_null`: takes arbitrary matrix $X$ as input, output a basis that spans the null space of $X$. The basis should be a numpy array or a list, containing several numpy array vectors.

---

In [32]:
def basis_null(A):
    # TODO: get a basis for the null space.
    A =  gaussian_elim(A)
    sol = solve(np.hstack((A, np.zeros((A.shape[0], 1)))))
    if sol.shape[1] > 1:
        return sol[:, 1:]
    return sol

In [33]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(basis_null(A))

# should return something like an identity matrix. The solution is not unique.

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
B = np.array([[16, 16, 11],
            [14, 19, 11],
            [11, 12, 19]])

print(basis_null(B))

# should return
# array([[0], [0], [0]])

[[0.]
 [0.]
 [0.]]


In [35]:
C = np.array([[ 0, 18, 16,  9, 6],
                [ 3, 14, 14,  6, 2],
                [14,  3,  4, 18, 8]])


print(basis_null(C))

# should return something like
# array([[-1.51875 , -0.8125], [-3.675,      -3.25], [ 3.571875, 3.28125], [ 1.      , 0], [ 0.      , 1]])
# the solution is not unique

[[-1.51875  -0.8125  ]
 [-3.675    -3.25    ]
 [ 3.571875  3.28125 ]
 [ 1.        0.      ]
 [ 0.        1.      ]]
