## COMP3670 Programming Assignment 1 - Linear Algebra
---

**Enter Your Student ID:** u7689173

**Your Name:** Aryan Odugoudar
    
**Deadline:**

**Submit:** Write your answers in this file, and submit a single Jupyter Notebook file (.ipynb) on Wattle. Rename this file with your student number as 'uXXXXXXX.ipynb'.

**Enter Discussion Partner IDs Below:**
You could add more IDs with the same markdown format above.



---
**Marking distribution for the assignment**

- Task1 = 10%
- Task2 = 50%
- Task3 = 40%

**You will get full marks if your program passes all the tests; you will get partial marks if it passes some cases. There is no process marks (we do not look into your codes).**

## Task 0: Introduction
---

**NOTE:** *This part of the first assignment is by necessity somewhat tedious as its primary purpose is to introduce syntax, how to access and understand the Numpy documentation and some very basic concepts. If you are already familiar with Numpy, you can just read the **TASK** headings and complete the questions without worrying about all the additional information. This is designed for people who have never seen Numpy before, so it's a very easy 1st year style introduction to just introduce syntax.*

*As this is a third year subject, it is assumed you already know to to program well (but may be unfamiliar with Python and Numpy).*

---

Arguably the most fundamental tool needed to engage with machine learning in Python is Numpy *(np)*. To include Numpy in any project, simply type the following line at the top of your python file:

In [1]:
# numpy
import numpy as np

!pip install sympy
import sympy as sp

# matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
!pip install rref

A Jupyter Notebook is divided into cells, each of which works like a Python module or Latex file. When a cell is run, any cells that follow it will have access to its results. Running the above cell will give all following cells access to the Numpy library.

-----------

   **TASK 0.1:** To run the above cell, select it by clicking on it, hold **shift** and press **return**. If you have succeeded, then the cell will print "Done" just above.


-----------

Numpy is a library of common mathematical data structures and algorithms used in machine learning. For example:

- It allows you to declare vectors and matrices, with all the associated mathematical operations like matrix vector products, matrix addition / subtraction.
- It provides convenient, efficient implementations of algorithms to solve matrix equations, find the inverse of a matrix or perform Eigen decomposition. The implementation of these algorithms is compiled from C code, making Numpy much faster than programming these algorithms yourself in Python.

You'll need to know Numpy inside and out. We'll start by getting you familiar with the easy to access online documentation and performing a few basic operations.

Below I have declared the matrices: 

$$A = 
\begin{bmatrix}
2&3\\
0&1\\
\end{bmatrix}
\\
x = 
\begin{bmatrix}
1\\
3\\
\end{bmatrix}
$$. 

---
**TASK 0.2:** Run the cell below and observe what it prints.


---
(If it throws an error, you have the wrong version of python installed. This entire course will use Python 3, not Python 2)



In [2]:
A = np.array([[2, 3], [0, 1]])
x = np.array([[1], [3]])

#Matrix Multiplication Example
b = A @ x
print('\nMatrix Multiplication')
print(b)


Matrix Multiplication
[[11]
 [ 3]]


The above code illustrates how to perform matrix multiplication. Memorise it. Below are some other basic operations you'll likely need over the coming semester:

In [3]:
#Matrix Addition Example
b = A + x
print('\nMatrix Addition')
print(b)

#Elementwise Multiplication Example
b = A * x
print('\nElementwise Matrix Multiplication')
print(b)

#Extract a single element of a matrix:
print('\nSingle Element Extraction')
b = A[0, 0]
print(b)

#Extract an entire column of a matrix:
print('\nColumn Extraction')
b = A[:, 0]
print(b)

#Extract an entire row of a matrix:
print('\nRow Extraction')
b = A[0, :]
print(b)

#Transpose of a matrix:
print('\nTranspose')
A_Transpose = A.T
print(A_Transpose)


Matrix Addition
[[3 4]
 [3 4]]

Elementwise Matrix Multiplication
[[2 3]
 [0 3]]

Single Element Extraction
2

Column Extraction
[2 0]

Row Extraction
[2 3]

Transpose
[[2 0]
 [3 1]]


## Task1: Solving a system of linear equations
---

A vital part of linear algebra is to know how to solve a system of linear equations. For e.g. 

$$a_{11}x_1+a_{12}x_2 \dots a_{1d}x_d=b_1$$
$$a_{21}x_1+a_{22}x_2 \dots a_{2d}x_d=b_2$$
$$\vdots$$
$$a_{n1}x_1+a_{n2}x_2 \dots a_{nd}x_d=b_n$$

The above system of linear equations can also be written down in a compact matrix form as follows:

$$AX = B$$

where,
$$A = \begin{bmatrix}
a_{11} & \dots & a_{1d}\\
\vdots & \ddots & \vdots \\
a_{n1} & \dots & a_{nd}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_1 \\ \vdots \\ b_n
\end{bmatrix}, \quad
X = \begin{bmatrix}
x_1 \\ \vdots \\ x_d
\end{bmatrix}.
$$

---
**Task 1.1**: Use numpy's solve function to compute X

---
**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

In [4]:
# define A,B
A = np.array([[10, 14, 4], [15, 2, 6], [7, 8, 18]])
B = np.array([[2], [1], [2]])

def solve_with_numpy(A,B):
    z=np.linalg.solve(A,B)
    return z

# show solution
X = solve_with_numpy(A,B)
print (X)

[[0.03185596]
 [0.10526316]
 [0.05193906]]


A more hands on way for solving for X, involves computing first computing the inverse of the matrix $A$

---
**Task 1.2**: Use numpy's inbuilt method for computing the inverse of the matrix $A$

---

**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

In [5]:
A = np.array([[7, 1], [15, 4]])
from numpy.linalg import inv

def find_inverse(A):
    z= inv(A)
    return z
    
A_inv = find_inverse(A)
print(A_inv)

[[ 0.30769231 -0.07692308]
 [-1.15384615  0.53846154]]


---
**Task 1.3**: Use the inverse of matrix $A$, to solve for $X$. **Note that you are only allowed to use the functions in 1.1 and 1.2. No other library functions are allowed**.

---

In [6]:
A = np.array([[5, 3], [2, 11]])
B = np.array([[16], [5]])
from numpy.linalg import inv

def solve_with_prev_tasks(A, B):
    Ainv= inv(A)
    z= Ainv @ B
    return z

X = solve_with_prev_tasks(A, B)
print(X)

[[ 3.28571429]
 [-0.14285714]]


But what if $A$ is not a square matrix?

---
**Task 1.4**: Compute the Moore-Penrose pseudo inverse for matrix $A$ and **use it to solve for $x$**. **Note that, you must not directly use `np.linalg.pinv` for computing the pseudo-inverse**.

---

In [50]:
A = np.array([[15, 1], [5, 10], [8, 2], [11, 19]])
B = np.array([[18], [15], [2], [8]])

def pseudo_inverse(A):
    U, D, V = np.linalg.svd(A)
    _D = np.zeros((A.shape[0], A.shape[1])).T
    _D[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))  
    A_Pseudo_Inverse = V.T.dot(_D).dot(U.T) 
    return A_Pseudo_Inverse 
    

def solve_with_pseudo_inverse(A, B):
    A_pseudo = pseudo_inverse(A)
    z = A_pseudo.dot(B) 
    return z

X = solve_with_pseudo_inverse(A, B)
    
print(pseudo_inverse(A))
print(X)

[[ 0.05648765 -0.00480567  0.02654076 -0.0032375 ]
 [-0.03300733  0.02444988 -0.01222494  0.04278729]]
[[0.97187421]
 [0.09046455]]


## Task 2: Solving a system of linear equations with Gaussian elimination

In the last task, we used numpy's inbulit functions to solve a system of linear equations. Lets do it without using these functions!

---
**Task 2.1**:  Complete the following gaussian elimnation function to compute the **reduced row-echelon form** of matrix $A$. You must implement the gaussian elimination algorithm yourself, not merely call someone else's library function. You **MUST NOT** copy codes from any source. Your function needs to work under **different shapes** of matrix. Negative zero is a result of the floating-point number standard. If you have some -0s instead of 0s, that should be fine.

---

In [8]:
def gaussian_elim(A):
    mat = A.copy()
    m, n = mat.shape
    R = np.array(mat, dtype=np.float64)

    # Check for duplicate rows.
    for i in range(m - 1):
        for j in range(i + 1, m):
            if np.allclose(R[i, :], R[j, :]):
                R[j, :] = R[j, :] - R[i, :]

    for r in range(min(m, n)):

        i = r
        while i < m and np.allclose(R[i, r], 0.0, atol=1e-15, rtol=1e-15):
            i += 1
        if i == m:
            R[np.abs(R) < 1e-10] = 0
            return R

        if np.allclose(R[i, r], 0.0):
            R[i, r] = 1e-10

        if i != r:
            R[[i, r], :] = R[[r, i], :]

        v = R[r, r]
        R[r, :] = R[r, :] / v

        for j in range(m):
            if j != r:
                lv = R[j, r]
                R[j, :] -= lv * R[r, :]
    R[np.abs(R) < 1e-10] = 0

    return R


In [9]:
A = np.array([[18, 18, 14, 15, 14, 19,  8,  7,  2, 11],
               [ 3,  7,  8,  8,  2,  2,  8, 17,  6,  8],
               [ 2,  8,  6,  4, 11, 10, 15, 11, 12,  3],
               [ 9,  4, 17,  6,  6, 12, 13,  0, 12,  2],
               [ 0,  3, 18,  0, 13,  6,  8, 13, 16, 15],
               [15, 16, 13,  9,  4, 17, 11,  0,  5, 18],
               [10,  4,  6, 12,  6, 18, 17,  7,  5,  6],
               [ 3, 12,  2,  4, 16,  1, 17,  8, 10,  2],
               [ 7,  8, 11,  4, 12, 14, 18, 14,  9, 16],
               [18, 13,  3, 19, 16,  9,  6,  8,  2, 15]])

print(gaussian_elim(A))
#print(A)

# The result should be an identity matrix

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
B = np.array([[ 5,  3, 14,  1,  2, 15,  1, 11],
               [ 3, 13,  5, 18, 16, 18, 12,  4],
               [ 1,  9, 12, 15, 15,  0,  7,  0],
               [18, 17,  5,  0, 11,  4, 17,  9]])

print(gaussian_elim(B))

#print(B,"\n")
# The result should look like
# [[  1.           0.           0.           0.          -2.77442593 20.86492571  -0.07248987   7.64520486]
#  [  0.           1.           0.           0.           3.44146781 -21.02183701   1.11661414  -7.36402521]
#  [  0.           0.           1.           0.           0.48694282 -2.83948672  -0.13552454  -0.68505178]
#  [  0.           0.           0.           1.          -1.26947321 13.49369653  -0.09004953   4.45677623]]

[[  1.           0.           0.           0.          -2.77442593
   20.86492571  -0.07248987   7.64520486]
 [  0.           1.           0.           0.           3.44146781
  -21.02183701   1.11661414  -7.36402521]
 [  0.           0.           1.           0.           0.48694282
   -2.83948672  -0.13552454  -0.68505178]
 [  0.           0.           0.           1.          -1.26947321
   13.49369653  -0.09004953   4.45677623]]


In [11]:
C = np.array([[ 3, 12, 17],
               [14, 19,  8],
               [ 1, 12,  7],
               [10, 17, 11],
               [ 6,  0, 12],
               [16,  3, 15],
               [16, 19, 18]])

print(gaussian_elim(C))


# The result should look like
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [51]:
# test your gaussian_elim function
def test_gaussian_elim():
    for i in range(100):
        m, n = np.random.randint(low=5, high=10, size=2)
        a = np.random.randn(m, n)
        sol1 = gaussian_elim(a)
        sol2 = np.array(sp.Matrix(a).rref()[0])
        if np.sum((sol1 - sol2) ** 2) > 1e-6:
            print(a, "\n")
            print(gaussian_elim(a), "\n")
            print(np.array(sp.Matrix(a).rref()[0]), "\n")
            return False
    test_cases = [np.array([[2, 0, 1, 1],
                            [2, 0, 1, 1],
                            [0, 0, 0, 0],
                            [1, 1, 1, 0]], dtype=np.float64),
                  np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]], dtype=np.float64),
                  ]
    for test in test_cases:
        sol1 = gaussian_elim(test)
        sol2 = np.array(sp.Matrix(test).rref()[0])
        if np.sum((sol1 - sol2) ** 2) > 1e-6:
            print(test, "\n")
            print(gaussian_elim(test), "\n")
            print(np.array(sp.Matrix(test).rref()[0]), "\n")
            return False
    return True
test_gaussian_elim()

True

---
**Task 2.2**: A system of linear equations is called homogeneous if the right hand side is the zero vector. Sometimes there will be only trivial solution, namely the zero vector. An example of this matrix is:
$$2x_1+4x_2 =0$$
$$2x_1+5x_2 =0$$
Sometimes there will be non-trivial solutions, e.g.,
$$2x_1+4x_2 =0$$
$$1x_1+2x_2 =0$$
The solution can be $x_1 =-2$, $x_2 =1$.
 
$A=\big(\begin{smallmatrix}
  2 & 4\\
  1 & 2
\end{smallmatrix}\big)$ is called coefficient matrix.
Your task is solving a homogeneous system of linear equations based on its reduced row-echelon form, i.e., the output of your *gaussian_elim* function in Task 2.1. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1. Your function needs to work under **different shapes** of $A$. 

The *solve_homogeneous* function should be according to the following specifications:
* Take as input the coefficient matrix $A$. 
* Return:
    - 0 if it only has trivial solution. Type: int.
    - otherwise, return any two different non-trivial solutions. Type: tuple((np.ndarray, Type: np.ndarray)).  Note that the dimensions of the np.ndarray should be 1, i.e., using one pair of square brackets. See demo outputs below.

In [13]:
def solve_homogeneous(A):
    # Z = np.array(sp.Matrix(A).rref()[0], dtype=np.float64)
    Z= gaussian_elim(A.copy())
    
    m, n = Z.shape
    nonTrivialSoln = [1 for i in range (n)]
    nonTrivialSoln2= [2 for i in range (n)]
    
    for row in Z:
        is_trivial = True
        if m<n:
            break
        for element in row[:-1]:
            if element != 0:
                is_trivial = False
                break
        
        if is_trivial and row[-1] != 0:
            return 0  
    
    
    for i in range(m):
        row = Z[i]
        if (not any(row)) : continue
        ans = 0
        ans2=0
        var_index = -1
        for j in range(n):
            element = row[j]
            if (element == 1 and  var_index == -1) :
                var_index = j
            elif (var_index != -1) : 
                ans+=element*(-1)
                ans2+=element*(-2)
                
        nonTrivialSoln[var_index]=ans
        nonTrivialSoln2[var_index]=ans2

    
    return (np.array(nonTrivialSoln), np.array(nonTrivialSoln2))

In [14]:
A = np.array([[ 6,  9,  1,  7],
               [17,  1,  3, 17],
               [ 8,  4,  9, 13],
               [18,  4, 18, 18]])
print(solve_homogeneous(A))
# The result should look like
# 0

0


In [15]:
B = np.array([[ 6,  8,  6, 15, 12],
           [17,  8,  8, 12,  2],
           [18, 15, 15,  7,  2],
           [ 7,  6, 10,  3, 18],
           [14,  4,  4,  2, 16]])
print(solve_homogeneous(B))
# The result should look like
# 0

0


In [16]:
C = np.array([[ 8, 18, 18],
               [14, 19, 15],
               [4,  9,  9]])

print(solve_homogeneous(C))
# The result should look like
# (array([ 0.72, -1.32,  1.  ]), array([ 1.44, -2.64,  2.  ]))
# Note they are not unique

(array([ 0.72, -1.32,  1.  ]), array([ 1.44, -2.64,  2.  ]))


In [17]:
D = np.array([[10,  3,  2,  8],
           [16,  5,  8,  5],
           [ 0,  0, 13, 16]])

print(solve_homogeneous(D))
#The result should look like
# ((array([-21.11538462,  68.53846154,  -1.23076923,   1.        ]), 
# array([-42.23076923, 137.07692308,  -2.46153846,   2.        ]))
# Note they are not unique

(array([-21.11538462,  68.53846154,  -1.23076923,   1.        ]), array([-42.23076923, 137.07692308,  -2.46153846,   2.        ]))


In [18]:
E = np.array([[ 2, 12,  2],
           [12,  8,  7],
           [14,  5, 17],
           [ 8, 10,  5]])

print(solve_homogeneous(E))
# The result should look like
# 0

0


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [52]:
def test_homogeneous_trivial():
    # test A with m>n and m=n but no dependent rows in it
    for i in range(1000):
        m = np.random.randint(low=4, high=6)
        n = np.random.randint(low=2, high=5)
        a = np.random.randn(m, n)
        res = solve_homogeneous(a)
        if res != 0:
            print(a, '\n')
            print(f' solution should be 0 but got {res}')
            return False
    # test A with m>n and there are dependent rows in it
    test_list = [
        np.array([[1, 2], [3, 4], [2, 4]]),
        np.array([[1, 2, 3], [2, 4, 6], [3, 4, 5], [4, 7, 9]]),
    ]
    for case in test_list:
        res = solve_homogeneous(case)
        if res != 0:
            print(a, '\n')
            print(f' solution should be 0 but got {res}')
            return False
    return True

def test_homogeneous_nontrivial():
    import random
    # test A with m=n and m<n
    for i in range(1000):
        m = np.random.randint(low=2, high=5)
        n = np.random.randint(low=4, high=6)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows or columns are dependent
        dpdt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[dpdt[0]]
        for row in dpdt:
            a[row] = duplicate
        x1 = np.expand_dims(solve_homogeneous(a)[0], axis=1)
        x2 = np.expand_dims(solve_homogeneous(a)[1], axis=1)
        if abs(np.sum(a @ x1)) > 1e-6 or abs(np.sum(a @ x2)) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
    # test A with m>n
    test_list = [
        np.array([[1, 2], [1, 2], [2, 4]]),
        np.array([[1, 2, 3], [3, 6, 9], [1, 2, 3], [4, 7, 9]]),
        np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    ]
    for case in test_list:
        x1 = np.expand_dims(solve_homogeneous(case)[0], axis=1)
        x2 = np.expand_dims(solve_homogeneous(case)[1], axis=1)
        if abs(np.sum(case @ x1)) > 1e-6 or abs(np.sum(case @ x2)) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
    return True

print(test_homogeneous_trivial())
print(test_homogeneous_nontrivial())

True
True


---
**Task 2.3**: A system of linear equations is called non-homogeneous if the right hand side is not the zero vector. A non-homogeneous system of linear equations has
* no solution, or
* a unique solution, or
* infinite number of solutions

Similar to Task 2.2, your task is solving a non-homogeneous system of linear equations. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1, however, you are allowed to use the functions you defined in Task 2.2. Your function needs to work under **different shapes** of augmented matrix $[A|b]$. 

The *solve_nonhomogeneous* function should be according to following specifications:
* Take as input the augmented matrix $[A|b]$. 
* Return:
    - None if it has no solution at all. Type: None.
    - the single solution if it only has one solution. Type: np.ndarray.
    - otherwise, return any two different solutions if it has more than one solutions. Type: tuple((np.ndarray, Type: np.ndarray)).
*  Note that the dimensions of the np.ndarray should be 1, especially, one pair of square brackets. See demo outputs below.    

In [54]:
def solve_nonhomogeneous(A_aug):
    threshold = 1e-16
    A_aug_rref = gaussian_elim(A_aug)
    A, b = A_aug_rref[:, :-1], A_aug_rref[:, -1]  # seperate the augumentation matrix
    m, n = A.shape
    res = [0 for _ in range(n)]

    row, col = 0, 0
    # search free variables
    while row < m and col < n:
        if abs(A[row][col] - 1) <= threshold:
            row += 1
            col += 1
            continue
        res[col] = 1  # set free variable to 1
        col += 1  # keep search from its left neighbor
    # check whether the last line has free variables
    # e.g. A = [[1, 0, 0], [0, 1, 2]], X_3 is a free varibale
    res[col:n] = [1] * (n - col)
    if 1 in res:
        free_var = [i for i in range(len(res)) if res[i] == 1]
        # print("index of free variable(s): {}\n".format(free_var))
    else:
        # if no free variable in RREF, return b if m == n
        # for m > n, return none if b[n:] is not a zero vector
        # return b[:n] otherwise
        # for m < n, there must be at least one free variable
        # print("no free variable\n")
        for i in range(min(m, n), m):
            if abs(b[i] - 0) > threshold:
                return None
        return b[:n]

    lead_var = [i for i in range(len(res)) if res[i] == 0]
    n_lead_var = len(lead_var)
    for i in range(n_lead_var, m):
        if abs(b[i] - 0) > threshold:
            return None

    # deep copy, set the value of free varibales to 2 instead of 1
    res_2 = [2 * x for x in res]
    for t in lead_var:
        # suppose A[1, :] = [0, 1, 0, 2], res = [0, 0, 0, 1], b = [0, 2, 0, 0]
        # then X_2 + 2 * X_4 = 2, X_2 = -2 * X_4 + 2= -2 * 1 + 2 = 0
        res[t] = -1 * sum([A[t, i] * res[i] for i in range(n)]) + b[t]
        res_2[t] = -1 * sum([A[t, i] * res_2[i] for i in range(n)]) + b[t]

    return (np.array(res), np.array(res_2))

In [55]:
A = np.array([[ 9,  5, 14,  3],
           [ 9,  1, 11,  0],
           [ 0,  4,  3,  2]])

print(solve_nonhomogeneous(A))
# The result should look like
# None

None


In [56]:
B = np.array([[ 9, 19,  2, 18],
           [ 5,  7,  3, 14],
           [14,  6,  1,  9]])

print(solve_nonhomogeneous(B))
# The result should look like
# [0.19444444 0.52777778 3.11111111]

[0.19444444 0.52777778 3.11111111]


In [57]:
C = np.array([[14, 14,  0, 18,  2, 11],
           [12, 12,  5,  1, 19, 13],
           [ 9,  3,  7,  1,  2, 11],
           [18, 10,  6, 12,  8, 16]])
print(solve_nonhomogeneous(C))
# The result should look like
# (array([-2.99214286,  0.35642857,  4.61571429,  2.55      ,  1.        ]), 
# array([-6.15785714,  0.29357143,  8.08428571,  4.95      ,  2.        ]))
# The results are not unique

(array([-2.99214286,  0.35642857,  4.61571429,  2.55      ,  1.        ]), array([-6.15785714,  0.29357143,  8.08428571,  4.95      ,  2.        ]))


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [58]:
def test_nonhomogeneous_no_solution():
    import random
    for i in range(1000):
        m = np.random.randint(low=3, high=6)
        n = np.random.randint(low=3, high=6)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows conflict
        cflt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[cflt[0]]
        for row in cflt:
            a[row] = duplicate
            a[row][-1] = np.random.normal(loc=a[row][-1])
        if solve_nonhomogeneous(a):
            print(a_, '\n')
            print(f'the solution should be None, but got {solve_nonhomogeneous(a)}')
            return False
    return True

def test_nonhomogeneous_single_solution():
    # test square A
    for i in range(1000):
        m = np.random.randint(low=3, high=6)
        n = m + 1
        a = np.random.randn(m, n)
        x = np.expand_dims(solve_nonhomogeneous(a), axis=1)
        if abs(np.sum(a[:, :-1] @ x) - np.sum(a[:, -1])) > 1e-6:
            print(a, '\n')
            print('the solution is not correct')
            return False
    test_list = [
        np.array([[1, 1, 1], [1, 3, 3], [2, 2, 2]]),
        np.array([[1, 2, 3, 2], [2, 4, 6, 4], [3, 6, 9, 6], [4, 7, 9, 10], [1, 2, 4, 7]]),
    ]
    # test A with m>n
    for case in test_list:
        x = np.expand_dims(solve_nonhomogeneous(case), axis=1)
        if abs(np.sum(case[:, :-1] @ x) - np.sum(case[:, -1])) > 1e-6:
            print(a, '\n')
            print('the solution is not correct')
            return False
    return True

def test_nonhomogeneous_infinite_solution():
    import random
    for i in range(1000):
        # test A with m=n and m<n whose rows are dependent
        m = np.random.randint(low=2, high=5)
        n = m + np.random.randint(low=1, high=4)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows or columns are dependent
        dpdt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[dpdt[0]]
        for row in dpdt:
            a[row] = duplicate
        x1 = np.expand_dims(solve_nonhomogeneous(a)[0], axis=1)
        x2 = np.expand_dims(solve_nonhomogeneous(a)[1], axis=1)
        if abs(np.sum(a[:, :-1] @ x1) - np.sum(a[:, -1])) > 1e-6 or abs(
                np.sum(a[:, :-1] @ x2) - np.sum(a[:, -1])) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
        # test A with m<n whose rows are not dependent
        if n > m + 1:
            x1 = np.expand_dims(solve_nonhomogeneous(a_)[0], axis=1)
            x2 = np.expand_dims(solve_nonhomogeneous(a_)[1], axis=1)
            if abs(np.sum(a[:, :-1] @ x1) - np.sum(a[:, -1])) > 1e-6 or abs(
                    np.sum(a[:, :-1] @ x2) - np.sum(a[:, -1])) > 1e-6 or (x1==x2).all():
                print(a_, '\n')
                print('the solutions are not correct')
                return False
    # test A with m>n whose rows are dependent
    test_list = [
        np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]]),
        np.array([[1, 2, 3, 4], [2, 4, 6, 8], [1, 4, 7, 9], [1, 2, 3, 4], [2, 4, 6, 8]]),
    ]
    for case in test_list:
        x1 = np.expand_dims(solve_nonhomogeneous(case)[0], axis=1)
        x2 = np.expand_dims(solve_nonhomogeneous(case)[1], axis=1)
        if abs(np.sum(case[:, :-1] @ x1) - np.sum(case[:, -1])) > 1e-6 or abs(
                np.sum(case[:, :-1] @ x2) - np.sum(case[:, -1])) > 1e-6 or (x1==x2).all():
            print(case, '\n')
            print('the solutions are not correct')
            return False
    return True

print(test_nonhomogeneous_no_solution())
print(test_nonhomogeneous_single_solution())
print(test_nonhomogeneous_infinite_solution())

True
True
True


## Task 3: Rank, Basis and Span

Given a matrix $X$, would it be possible for you to programmably determine its rank, null space and column space? In this question, you are tasked at **1) finding the rank and the dimension of the null space $X$, 2) finding the basis that spans the column space of $X$, and 3) finding the basis that spans the null space of $X$.**

---
**Task 3.1**: Implement two functions `rank`, `dim_null`.

`rank`: takes arbitrary matrix $X$ as input, output its rank.

`dim_null`: takes arbitrary matrix $X$ as input, output the dimension of its null space

**Note: If you didn't get Gaussian Elimination in task2, you may use the library function `sp.Matrix(X).rref()` to get the reduced row echelon form of $X$. But, you must not use other library functions that can solve questions directly.**

In [25]:
def rank(A):
    Arref, p = sp.Matrix(A).rref()
    
    NonZeroRows = 0
    for row in range(Arref.shape[0]):
        if any(Arref[row, :]):
            NonZeroRows += 1
    
    return NonZeroRows
    
def dim_null(A):
    A_rref, p = sp.Matrix(A).rref()
    
    colmn = A.shape[1]
    pivots = len(p)
    dim_null_space = colmn - pivots
    
    return dim_null_space

In [26]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(rank(A))
print(dim_null(A))

# you should get
# 0
# 3

0
3


In [27]:
B = np.array([[16,  8, 12,  8,  5],
               [ 0,  7,  9, 14,  2],
               [14, 12, 13, 15, 14],
               [13, 18, 16, 19, 12]])

print(rank(B))
print(dim_null(B))

# you should get
# 4
# 1

4
1


In [28]:
C = np.array([[ 1,  8,  4],
               [ 0,  0, 11],
               [15,  2, 11],
               [12,  0,  3]])

print(rank(C))
print(dim_null(C))

# you should get
# 3
# 0

3
0


Make sure you pass the following test. Here we only provide the test for the rank.

In [29]:
def test_rank():
    for _ in range(1000):
        rnd_h = np.random.randint(1, 10)
        rnd_w = np.random.randint(1, 10)
        rnd_mat = np.random.choice(100, [rnd_h, rnd_w], replace=True).astype(np.float64)
        if rank(rnd_mat) != np.linalg.matrix_rank(rnd_mat):
            return False
    return True
test_rank()

True



---
**Task 3.2**: Implement `basis_col`.

`basis_col`: takes arbitrary matrix $X$ as input, output a basis that spans the column space of $X$. The basis should be a numpy array or a list, containing several numpy array vectors. 

---

In [59]:
def basis_col(A):
    m, n = A.shape
    basis = []

    for col in range(min(m,n)):
        linearInd = True

        for prev_col in basis:
            if np.array_equal(A[:, col], prev_col):
                linearInd = False
                break
        
        for prev_col in basis[col+1:]:
            if np.array_equal(A[:, col], prev_col):
                linearInd = False
                break
        
        if linearInd:
            basis.append(A[:, col])
    
    return np.array(basis).T


In [60]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(basis_col(A))

# should return 
# array([[0], [0], [0]])

[[0]
 [0]
 [0]]


In [61]:
B = np.array([[13, 11,  6,  9,  6],
            [ 0, 12, 16, 11, 14],
            [ 5, 15,  8,  3,  0],
            [16,  3,  1, 14,  5]])

print(basis_col(B))

# should return something like
# array([[13, 11, 6, 9], [0, 12, 16, 11], [5, 15, 8, 3], [16, 3, 1, 14]])
# the solution is not unique

[[13 11  6  9]
 [ 0 12 16 11]
 [ 5 15  8  3]
 [16  3  1 14]]


In [62]:
C = np.array([[1, 1], 
              [1, 1], 
              [1, 1]])

print(basis_col(C))
# should return something like
# array([[1], [1], [1]])
# the solution is not unique

[[1]
 [1]
 [1]]


We will use more test cases when testing your implementation.

---
**Task 3.3**: Implement `basis_null`.

`basis_null`: takes arbitrary matrix $X$ as input, output a basis that spans the null space of $X$. The basis should be a numpy array or a list, containing several numpy array vectors.

---

In [63]:
def basis_null(X):

    m, n = X.shape

    # Reduce X to row echelon form using Gaussian elimination.
    R = gaussian_elim(X)

    # Find the pivot rows.
    pivot_rows = []
    for i in range(m):
        if not np.allclose(R[i, :], 0.0):
            pivot_rows.append(i)

    # If there are no pivot rows, then the null space is all of the space.
    if not pivot_rows and not np.allclose(R, np.eye(m)):
        return np.eye(m)

    # The basis vectors are the rows of R corresponding to the pivot rows.
    rank_mat = rank(R)
    free_vars = n - rank_mat
    if free_vars == 0:
        return np.zeros(shape=(1, n)).T
    
    solution_matrix = np.zeros(shape=(n, free_vars))
    for i in range(m) :
        for j in range(rank_mat, n) : 
            solution_matrix[i, j-rank_mat] = R[i, j] * (-1)
    
    for i in range(rank_mat, n) :
        solution_matrix[i][i-rank_mat] = 1
    
    

    return np.array(solution_matrix)


In [64]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])
print(basis_null(A))

# should return something like an identity matrix. The solution is not unique.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
B = np.array([[16, 16, 11],
            [14, 19, 11],
            [11, 12, 19]])

print(basis_null(B))

# should return
# array([[0], [0], [0]])

[[0.]
 [0.]
 [0.]]


In [66]:
C = np.array([[ 0, 18, 16,  9, 6],
                [ 3, 14, 14,  6, 2],
                [14,  3,  4, 18, 8]])

print(basis_null(C))

# should return something like
# array([[-1.51875 , -0.8125], [-3.675,      -3.25], [ 3.571875, 3.28125], [ 1.      , 0], [ 0.      , 1]])
# the solution is not unique

[[-1.51875  -0.8125  ]
 [-3.675    -3.25    ]
 [ 3.571875  3.28125 ]
 [ 1.        0.      ]
 [ 0.        1.      ]]


We will use more test cases when testing your implementation.